server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8888/eureka/

spring.datasource.url=jdbc:h2:mem:BoardgamePJB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=master
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
